################################# Default configuration ###################
baseURL = "https://cpconsultants.github.io"
title = "Chennai Pharma Consultants"
theme = "airspace-hugo"
themesDir = "themes"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

################################# Outputs #################################
# hugo outputs
[outputs]
home = ["HTML"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/logo2.png"
logo_width = "220px"

# Meta data
description = "Your trusted partner in project planning"
author = "Natesan Venkatesh"
# Contact Information
mobile = "91-9445519674"
email = "projectsvenkat@email.com"
location = "Chennai India"
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = false
gmap_api = ""
map_latitude = "13.015844"
map_longitude = "80.227427"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2022 [CPC](https://cpconsultant.in) All Rights Reserved"


######################### english navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About"
URL = "about"
weight = 2

[[Languages.en.menu.main]]
name = "clients"
URL = "project"
weight = 3

#[[Languages.en.menu.main]]
#name = "Blog"
#URL = "blog"
#weight = 4

#[[Languages.en.menu.main]]
#weight = 5
#name = "Pages"
#hasChildren = true

  #[[Languages.en.menu.main]]
  #parent = "Pages"
  #name = "FAQ"
  #URL = "faq"

  #[[Languages.en.menu.main]]
  #parent = "Pages"
  #name = "Pricing"
  #URL = "pricing"

  #[[Languages.en.menu.main]]
  #parent = "Pages"
  #name = "Service"
  #URL = "service"


[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 6

######################### Footer Menu #############################

[[Languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[Languages.en.menu.footer]]
name = "Clients"
URL = "project"
weight = 2

[[Languages.en.menu.footer]]
name = "Service"
URL = "service"
weight = 3

[[Languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6